name: Lint
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/lint.yml'
      - 'mk/**'
      - '.gitignore'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/lint.yml'
      - 'mk/**'
      - '.gitignore'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
